<?php
class Headers {
	private $arr_heading;
	function __construct() {
		# initialization
			// keyword, header
		$this->arr_heading = array(
				array("vip_remonty_kvartir_v_samare", "VIP ремонт квартир в Санкт-Петербурге"),
				array("dizajn_studiya_evroremont_v_samare", "Дизайнерский ремонт в Санкт-Петербурге"),
				array("dizajnerskaya_vnutrennyaya_otdelka_doma_v_samare", "Дизайнерская внутренняя отделка дома в Санкт-Петербурге"),
				array("dizajnerskaya_otdelka_v_samare", "Дизайнерская отделка в Санкт-Петербурге"),
				array("dizajnerskaya_otdelka_domov_v_samare", "Дизайнерская отделка домов в Санкт-Петербурге"),
				array("dizajnerskaya_otdelka_kvartir_v_samare", "Дизайнерская отделка квартир в Санкт-Петербурге"),
				array("dizajnerskaya_otdelka_pomeshhenij_v_samare", "Дизайнерская отделка помещений в Санкт-Петербурге"),
				array("dizajnerskij_remont_v_samare", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_1_kvartiry_v_samare", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_1_komnatnoj_kvartiry_v_samare", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_2_komnatnoj_kvartiry_v_samare", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_2_x_komnatnoj_kvartiry_v_samare", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_3_komnatnoj_kvartiry_v_samare", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_3_x_komnatnoj_kvartiry_v_samare", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_v_novostrojke_v_samare", "Дизайнерский ремонт новостроек в Санкт-Петербурге"),
				array("dizajnerskij_remont_vnutrennij_v_samare", "Дизайнерский ремонт-отделка в Санкт-Петербурге"),
				array("dizajnerskij_remont_dvuxkomnatnyx_kvartir_v_samare", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_domov_v_samare", "Дизайнерский ремонт домов в Санкт-Петербурге"),
				array("dizajnerskij_remont_kvartir_v_samare", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_kvartir_pod_klyuch_v_samare", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_kvartir_studij_v_samare", "Дизайнерский ремонт квартир студий в Санкт-Петербурге"),
				array("dizajnerskij_remont_kvartir_ceny_v_samare", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_kvartiry_s_nulya_v_novostrojke_v_samare", "Дизайнерский ремонт новостроек в Санкт-Петербурге"),
				array("dizajnerskij_remont_kottedzhej_v_samare", "Дизайнерский ремонт коттеджей в Санкт-Петербурге"),
				array("dizajnerskij_remont_malogabaritnyx_kvartir_v_samare", "Дизайнерский ремонт малогабаритных квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_novostroek_v_samare", "Дизайнерский ремонт новостроек в Санкт-Петербурге"),
				array("dizajnerskij_remont_odnokomnatnoj_kvartiry_v_samare", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_odnokomnatnoj_kvartiry_cena_v_samare", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_pod_klyuch_v_samare", "Дизайнерский ремонт под ключ в Санкт-Петербурге"),
				array("dizajnerskij_remont_pod_klyuch_stoimost_v_samare", "Дизайнерский ремонт под ключ в Санкт-Петербурге"),
				array("dizajnerskij_remont_pomeshhenij_v_samare", "Дизайнерский ремонт помещений в Санкт-Петербурге"),
				array("dizajnerskij_remont_studij_v_samare", "Дизайнерский ремонт студий в Санкт-Петербурге"),
				array("dizajnerskij_remont_trexkomnatnoj_kvartiry_v_samare", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dorogaya_otdelka_domov_v_samare", "Дорогая и высококачественная отделка домов в Санкт-Петербурге"),
				array("dorogaya_otdelka_kvartir_v_samare", "Дорогая и высококачественная отделка квартир в Санкт-Петербурге"),
				array("dorogaya_otdelka_pomeshhenij_v_samare", "Дорогая и высококачественная отделка помещений в Санкт-Петербурге"),
				array("dorogoj_remont_domov_v_samare", "Дорогой и высококачественный ремонт домов в Санкт-Петербурге"),
				array("dorogoj_remont_kvartir_v_samare", "Дорогой и высококачественный ремонт квартир в Санкт-Петербурге"),
				array("dorogoj_remont_novostroek_v_samare", "Дорогой и высококачественный ремонт новостроек в Санкт-Петербурге"),
				array("dorogoj_remont_pod_klyuch_v_samare", "Дорогой и высококачественный ремонт под ключ в Санкт-Петербурге"),
				array("dorogoj_remont_pomeshhenij_v_samare", "Дорогой и высококачественный ремонт помещений в Санкт-Петербурге"),
				array("evro_otdelka_v_samare", "Евро отделка помещений в Санкт-Петербурге"),
				array("evro_otdelka_kvartiry_v_samare", "Евро отделка квартиры в Санкт-Петербурге"),
				array("evro_remont_3_komnatnoj_kvartiry_v_samare", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evro_remont_v_xrushhevke_v_samare", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evro_remont_dvuxkomnatnyx_kvartir_v_samare", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evro_remont_dlya_odnokomnatnoj_kvartiry_v_samare", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evro_remont_domov_v_samare", "Евро ремонт домов в Санкт-Петербурге"),
				array("evro_remont_kvartir_v_samare", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evro_remont_kvartir_pod_klyuch_v_samare", "Евро ремонт квартир под ключ в Санкт-Петербурге"),
				array("evro_remont_kvartir_cena_v_samare", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evro_remont_kuxni_i_kvartiry_v_samare", "Евро ремонт кухни и квартиры в Санкт-Петербурге"),
				array("evro_remont_po_domu_v_samare", "Евро ремонт по дому в Санкт-Петербурге"),
				array("evro_remont_pod_klyuch_v_samare", "Евро ремонт под ключ в Санкт-Петербурге"),
				array("evro_remont_pomeshhenij_v_samare", "Евро ремонт помещений в Санкт-Петербурге"),
				array("evro_remont_rascenki_v_samare", "Евро ремонт в Санкт-Петербурге"),
				array("evro_remont_ceny_v_samare", "Евро ремонт в Санкт-Петербурге"),
				array("evro_remonty_v_domax_v_samare", "Евро ремонт дома в Санкт-Петербурге"),
				array("evro_remonty_v_kvartirax_v_samare", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evro_remonty_v_kvartirax_cena_v_samare", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evrootdelka_kvartir_v_samare", "Евроотделка квартир в Санкт-Петербурге"),
				array("evroremont_1_komnatnoj_kvartiry_v_samare", "Евроремонт 1 комнатной квартиры в Санкт-Петербурге"),
				array("evroremont_2_komnatnoj_kvartiry_v_samare", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evroremont_2_x_komnatnoj_kvartiry_v_samare", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evroremont_3_x_komnatnoj_kvartiry_v_samare", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evroremont_v_chastnom_dome_v_samare", "Евроремонт в частном доме в Санкт-Петербурге"),
				array("evroremont_dvuxkomnatnoj_kvartiry_v_samare", "Евроремонт двухкомнатной квартиры в Санкт-Петербурге"),
				array("evroremont_domov_v_samare", "Евроремонт домов в Санкт-Петербурге"),
				array("evroremont_kvartir_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("evroremont_kvartir_v_novostrojke_v_samare", "Евроремонт квартир новостроек в Санкт-Петербурге"),
				array("evroremont_kvartir_nedorogo_v_samare", "Евроремонт квартир недорого в Санкт-Петербурге"),
				array("evroremont_kvartir_pod_klyuch_v_samare", "Евроремонт квартир под ключ в Санкт-Петербурге"),
				array("evroremont_kvartir_pod_klyuch_ceny_v_samare", "Евроремонт квартир под ключ в Санкт-Петербурге"),
				array("evroremont_kvartir_ceny_v_samare", "Евроремонт квартир под ключ в Санкт-Петербурге"),
				array("evroremont_kottedzhej_v_samare", "Евроремонт коттеджей в Санкт-Петербурге"),
				array("evroremont_nedorogo_v_samare", "Евроремонт недорого в Санкт-Петербурге"),
				array("evroremont_novostroek_v_samare", "Евроремонт новостроек в Санкт-Петербурге"),
				array("evroremont_novostrojki_v_samare", "Евроремонт новостройки в Санкт-Петербурге"),
				array("evroremont_odnokomnatnoj_kvartiry_v_samare", "Евроремонт однокомнатной квартиры в Санкт-Петербурге"),
				array("evroremont_odnokomnatnoj_kvartiry_cena_v_samare", "Евроремонт однокомнатной квартиры в Санкт-Петербурге"),
				array("evroremont_otdelka_v_samare", "Евроремонт отделка в Санкт-Петербурге"),
				array("evroremont_otdelka_pomeshhenij_v_samare", "Евроремонт отделка помещений в Санкт-Петербурге"),
				array("evroremont_pod_klyuch_v_samare", "Евроремонт под ключ в Санкт-Петербурге"),
				array("evroremont_pod_klyuch_ceny_v_samare", "Евроремонт под ключ цены в Санкт-Петербурге"),
				array("evroremont_pomeshhenij_v_samare", "Евроремонт помещений в Санкт-Петербурге"),
				array("evroremont_prajs_v_samare", "Евроремонт помещений в Санкт-Петербурге"),
				array("evroremont_rascenki_v_samare", "Евроремонт помещений в Санкт-Петербурге"),
				array("evroremont_remont_domov_v_samare", "Евроремонт домов в Санкт-Петербурге"),
				array("evroremont_remont_novostroek_v_samare", "Евроремонт новостроек в Санкт-Петербурге"),
				array("evroremont_remont_pod_klyuch_v_samare", "Евроремонт под ключ в Санкт-Петербурге"),
				array("evroremont_remont_pomeshhenij_v_samare", "Евроремонт помещений в Санкт-Петербурге"),
				array("evroremont_stoimost_rabot_v_samare", "Евроремонт помещений в Санкт-Петербурге"),
				array("evroremont_taunxausa_v_samare", "Евроремонт таунхауса в Санкт-Петербурге"),
				array("evroremont_trexkomnatnoj_kvartiry_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("evroremont_xrushhevki_v_samare", "Евроремонт хрущевок в Санкт-Петербурге"),
				array("evroremont_cena_za_kvadratnyj_metr_v_samare", "Евроремонт помещений в Санкт-Петербурге"),
				array("evroremont_cena_za_metr_v_samare", "Евроремонт помещений в Санкт-Петербурге"),
				array("evroremont_ceny_v_samare", "Евроремонт помещений в Санкт-Петербурге"),
				array("kapitalnyj_evroremont_v_samare", "Капитальный евроремонт в Санкт-Петербурге"),
				array("kapitalnyj_remont_kvartir_evroremont_v_samare", "Капитальный евроремонт квартир в Санкт-Петербурге"),
				array("kompaniya_elitnyj_remont_v_samare", "Элитный ремонт в Санкт-Петербурге"),
				array("lyuks_otdelka_pomeshhenij_v_samare", "Люкс отделка помещений в Санкт-Петербурге"),
				array("lyuks_remont_domov_v_samare", "Люкс ремонт домов в Санкт-Петербурге"),
				array("lyuks_remont_pomeshhenij_v_samare", "Люкс ремонт помещений в Санкт-Петербурге"),
				array("otdelka_kvartir_evroremont_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("prajs_list_na_evroremont_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("rascenki_evrootdelki_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("rascenki_na_evro_remonty_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("remont_kvartir_dorogo_v_samare", "Ремонт квартир дорого и качественно в Санкт-Петербурге"),
				array("remont_kvartir_dorogo_i_kachestvenno_v_samare", "Ремонт квартир дорого и качественно в Санкт-Петербурге"),
				array("remont_kvartir_evroremont_v_samare", "Ремонт квартир евроремонт в Санкт-Петербурге"),
				array("remont_kvartir_evroremont_dizajn_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("remont_kvartir_otdelka_evroremont_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("remont_kvartir_pod_evro_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("remont_kvartir_ceny_evroremont_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("remont_kvartiry_lyuks_v_samare", "Ремонт квартир класса люкс в Санкт-Петербурге"),
				array("remont_elitnyx_domov_v_samare", "Ремонт элитных домов в Санкт-Петербурге"),
				array("sdelat_dizajnerskij_remont_v_kvartire_v_samare", "Дизайнерский ремонт в квартире в Санкт-Петербурге"),
				array("sdelat_elitnyj_remont_v_samare", "Элитный ремонт в Санкт-Петербурге"),
				array("skolko_stoit_dizajnerskij_remont_kvartiry_v_samare", "Дизайнерский ремонт квартиры в Санкт-Петербурге"),
				array("skolko_stoit_evro_remont_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("skolko_stoit_evroremont_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("skolko_stoit_evroremont_dvuxkomnatnoj_kvartiry_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("skolko_stoit_evroremont_kvartiry_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("skolko_stoit_evroremont_odnokomnatnoj_kvartiry_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("skolko_stoit_evroremont_trexkomnatnoj_kvartiry_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("skolko_stoit_kvadratnyj_metr_evroremonta_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("smeta_na_evroremont_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("smeta_na_evroremont_kvartiry_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("sovremennyj_dizajnerskij_remont_kvartir_v_samare", "Современный дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("srednyaya_cena_evroremonta_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("stoimost_dizajnerskogo_remonta_kvartiry_v_samare", "Современный дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("stoimost_evro_remonta_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("stoimost_evroremonta_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("stoimost_evroremonta_za_kvadratnyj_metr_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("stoimost_evroremonta_kvartiry_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("stoimost_evroremonta_pod_klyuch_v_samare", "Евроремонт квартир в Санкт-Петербурге"),
				array("stoimost_elitnogo_remonta_v_samare", "Элитный ремонт в Санкт-Петербурге"),
				array("studiya_elitnogo_remonta_v_samare", "Элитный ремонт в Санкт-Петербурге"),
				array("elitnaya_otdelka_v_samare", "Элитная отделка в Санкт-Петербурге"),
				array("elitnaya_otdelka_domov_v_samare", "Элитная отделка домов в Санкт-Петербурге"),
				array("elitnaya_otdelka_kvartir_v_samare", "Элитная отделка квартир в Санкт-Петербурге"),
				array("elitnaya_otdelka_kvartir_pod_klyuch_v_samare", "Элитная отделка квартир под ключ в Санкт-Петербурге"),
				array("elitnaya_otdelka_kottedzhej_v_samare", "Элитная отделка коттеджей в Санкт-Петербурге"),
				array("elitnaya_otdelka_kottedzhej_pod_klyuch_v_samare", "Элитная отделка коттеджей под ключ в Санкт-Петербурге"),
				array("elitnaya_otdelka_pomeshhenij_v_samare", "Элитная отделка помещений в Санкт-Петербурге"),
				array("elitnye_otdelochnye_raboty_v_samare", "Элитные отделочные работы в Санкт-Петербурге"),
				array("elitnyj_evroremont_v_samare", "Элитный евроремонт в Санкт-Петербурге"),
				array("elitnyj_remont_kvartir_v_samare", "Элитный ремонт квартир в Санкт-Петербурге"),
				array("elitnyj_remont_kvartir_i_domov_v_samare", "Элитный ремонт квартир и домов в Санкт-Петербурге"),
				array("elitnyj_remont_kvartir_pod_klyuch_v_samare", "Элитный ремонт квартир под ключ в Санкт-Петербурге"),
				array("elitnyj_remont_kvartir_stoimost_v_samare", "Элитный ремонт квартир стоимость в Санкт-Петербурге"),
				array("elitnyj_remont_kvartir_ceny_v_samare", "Элитный ремонт квартир цены в Санкт-Петербурге"),
				array("elitnyj_remont_kottedzhej_v_samare", "Элитный ремонт коттеджей в Санкт-Петербурге"),
				array("elitnyj_remont_kottedzhej_pod_klyuch_v_samare", "Элитный ремонт коттеджей под ключ в Санкт-Петербурге"),
				array("elitnyj_remont_pod_klyuch_v_samare", "Элитный ремонт под ключ в Санкт-Петербурге"),
				array("vip_remonty_kvartir", "VIP ремонт квартир в Санкт-Петербурге"),
				array("dizajn_studiya_evroremont", "Дизайнерский ремонт в Санкт-Петербурге"),
				array("dizajnerskaya_vnutrennyaya_otdelka_doma", "Дизайнерская внутренняя отделка дома в Санкт-Петербурге"),
				array("dizajnerskaya_otdelka", "Дизайнерская отделка в Санкт-Петербурге"),
				array("dizajnerskaya_otdelka_domov", "Дизайнерская отделка домов в Санкт-Петербурге"),
				array("dizajnerskaya_otdelka_kvartir", "Дизайнерская отделка квартир в Санкт-Петербурге"),
				array("dizajnerskaya_otdelka_pomeshhenij", "Дизайнерская отделка помещений в Санкт-Петербурге"),
				array("dizajnerskij_remont", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_1_kvartiry", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_1_komnatnoj_kvartiry", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_2_komnatnoj_kvartiry", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_2_x_komnatnoj_kvartiry", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_3_komnatnoj_kvartiry", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_3_x_komnatnoj_kvartiry", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_v_novostrojke", "Дизайнерский ремонт новостроек в Санкт-Петербурге"),
				array("dizajnerskij_remont_vnutrennij", "Дизайнерский ремонт-отделка в Санкт-Петербурге"),
				array("dizajnerskij_remont_dvuxkomnatnyx_kvartir", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_domov", "Дизайнерский ремонт домов в Санкт-Петербурге"),
				array("dizajnerskij_remont_kvartir", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_kvartir_pod_klyuch", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_kvartir_studij", "Дизайнерский ремонт квартир студий в Санкт-Петербурге"),
				array("dizajnerskij_remont_kvartir_ceny", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_kvartiry_s_nulya_v_novostrojke", "Дизайнерский ремонт новостроек в Санкт-Петербурге"),
				array("dizajnerskij_remont_kottedzhej", "Дизайнерский ремонт коттеджей в Санкт-Петербурге"),
				array("dizajnerskij_remont_malogabaritnyx_kvartir", "Дизайнерский ремонт малогабаритных квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_novostroek", "Дизайнерский ремонт новостроек в Санкт-Петербурге"),
				array("dizajnerskij_remont_odnokomnatnoj_kvartiry", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_odnokomnatnoj_kvartiry_cena", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dizajnerskij_remont_pod_klyuch", "Дизайнерский ремонт под ключ в Санкт-Петербурге"),
				array("dizajnerskij_remont_pod_klyuch_stoimost", "Дизайнерский ремонт под ключ в Санкт-Петербурге"),
				array("dizajnerskij_remont_pomeshhenij", "Дизайнерский ремонт помещений в Санкт-Петербурге"),
				array("dizajnerskij_remont_studij", "Дизайнерский ремонт студий в Санкт-Петербурге"),
				array("dizajnerskij_remont_trexkomnatnoj_kvartiry", "Дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("dorogaya_otdelka_domov", "Дорогая и высококачественная отделка домов в Санкт-Петербурге"),
				array("dorogaya_otdelka_kvartir", "Дорогая и высококачественная отделка квартир в Санкт-Петербурге"),
				array("dorogaya_otdelka_pomeshhenij", "Дорогая и высококачественная отделка помещений в Санкт-Петербурге"),
				array("dorogoj_remont_domov", "Дорогой и высококачественный ремонт домов в Санкт-Петербурге"),
				array("dorogoj_remont_kvartir", "Дорогой и высококачественный ремонт квартир в Санкт-Петербурге"),
				array("dorogoj_remont_novostroek", "Дорогой и высококачественный ремонт новостроек в Санкт-Петербурге"),
				array("dorogoj_remont_pod_klyuch", "Дорогой и высококачественный ремонт под ключ в Санкт-Петербурге"),
				array("dorogoj_remont_pomeshhenij", "Дорогой и высококачественный ремонт помещений в Санкт-Петербурге"),
				array("evro_otdelka", "Евро отделка помещений в Санкт-Петербурге"),
				array("evro_otdelka_kvartiry", "Евро отделка квартиры в Санкт-Петербурге"),
				array("evro_remont_3_komnatnoj_kvartiry", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evro_remont_v_xrushhevke", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evro_remont_dvuxkomnatnyx_kvartir", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evro_remont_dlya_odnokomnatnoj_kvartiry", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evro_remont_domov", "Евро ремонт домов в Санкт-Петербурге"),
				array("evro_remont_kvartir", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evro_remont_kvartir_pod_klyuch", "Евро ремонт квартир под ключ в Санкт-Петербурге"),
				array("evro_remont_kvartir_cena", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evro_remont_kuxni_i_kvartiry", "Евро ремонт кухни и квартиры в Санкт-Петербурге"),
				array("evro_remont_po_domu", "Евро ремонт по дому в Санкт-Петербурге"),
				array("evro_remont_pod_klyuch", "Евро ремонт под ключ в Санкт-Петербурге"),
				array("evro_remont_pomeshhenij", "Евро ремонт помещений в Санкт-Петербурге"),
				array("evro_remont_rascenki", "Евро ремонт в Санкт-Петербурге"),
				array("evro_remont_ceny", "Евро ремонт в Санкт-Петербурге"),
				array("evro_remonty_v_domax", "Евро ремонт дома в Санкт-Петербурге"),
				array("evro_remonty_v_kvartirax", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evro_remonty_v_kvartirax_cena", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evrootdelka_kvartir", "Евроотделка квартир в Санкт-Петербурге"),
				array("evroremont_1_komnatnoj_kvartiry", "Евроремонт 1 комнатной квартиры в Санкт-Петербурге"),
				array("evroremont_2_komnatnoj_kvartiry", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evroremont_2_x_komnatnoj_kvartiry", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evroremont_3_x_komnatnoj_kvartiry", "Евро ремонт квартир в Санкт-Петербурге"),
				array("evroremont_v_chastnom_dome", "Евроремонт в частном доме в Санкт-Петербурге"),
				array("evroremont_dvuxkomnatnoj_kvartiry", "Евроремонт двухкомнатной квартиры в Санкт-Петербурге"),
				array("evroremont_domov", "Евроремонт домов в Санкт-Петербурге"),
				array("evroremont_kvartir", "Евроремонт квартир в Санкт-Петербурге"),
				array("evroremont_kvartir_v_novostrojke", "Евроремонт квартир новостроек в Санкт-Петербурге"),
				array("evroremont_kvartir_nedorogo", "Евроремонт квартир недорого в Санкт-Петербурге"),
				array("evroremont_kvartir_pod_klyuch", "Евроремонт квартир под ключ в Санкт-Петербурге"),
				array("evroremont_kvartir_pod_klyuch_ceny", "Евроремонт квартир под ключ в Санкт-Петербурге"),
				array("evroremont_kvartir_ceny", "Евроремонт квартир под ключ в Санкт-Петербурге"),
				array("evroremont_kottedzhej", "Евроремонт коттеджей в Санкт-Петербурге"),
				array("evroremont_nedorogo", "Евроремонт недорого в Санкт-Петербурге"),
				array("evroremont_novostroek", "Евроремонт новостроек в Санкт-Петербурге"),
				array("evroremont_novostrojki", "Евроремонт новостройки в Санкт-Петербурге"),
				array("evroremont_odnokomnatnoj_kvartiry", "Евроремонт однокомнатной квартиры в Санкт-Петербурге"),
				array("evroremont_odnokomnatnoj_kvartiry_cena", "Евроремонт однокомнатной квартиры в Санкт-Петербурге"),
				array("evroremont_otdelka", "Евроремонт отделка в Санкт-Петербурге"),
				array("evroremont_otdelka_pomeshhenij", "Евроремонт отделка помещений в Санкт-Петербурге"),
				array("evroremont_pod_klyuch", "Евроремонт под ключ в Санкт-Петербурге"),
				array("evroremont_pod_klyuch_ceny", "Евроремонт под ключ цены в Санкт-Петербурге"),
				array("evroremont_pomeshhenij", "Евроремонт помещений в Санкт-Петербурге"),
				array("evroremont_prajs", "Евроремонт помещений в Санкт-Петербурге"),
				array("evroremont_rascenki", "Евроремонт помещений в Санкт-Петербурге"),
				array("evroremont_remont_domov", "Евроремонт домов в Санкт-Петербурге"),
				array("evroremont_remont_novostroek", "Евроремонт новостроек в Санкт-Петербурге"),
				array("evroremont_remont_pod_klyuch", "Евроремонт под ключ в Санкт-Петербурге"),
				array("evroremont_remont_pomeshhenij", "Евроремонт помещений в Санкт-Петербурге"),
				array("evroremont_stoimost_rabot", "Евроремонт помещений в Санкт-Петербурге"),
				array("evroremont_taunxausa", "Евроремонт таунхауса в Санкт-Петербурге"),
				array("evroremont_trexkomnatnoj_kvartiry", "Евроремонт квартир в Санкт-Петербурге"),
				array("evroremont_xrushhevki", "Евроремонт хрущевок в Санкт-Петербурге"),
				array("evroremont_cena_za_kvadratnyj_metr", "Евроремонт помещений в Санкт-Петербурге"),
				array("evroremont_cena_za_metr", "Евроремонт помещений в Санкт-Петербурге"),
				array("evroremont_ceny", "Евроремонт помещений в Санкт-Петербурге"),
				array("kapitalnyj_evroremont", "Капитальный евроремонт в Санкт-Петербурге"),
				array("kapitalnyj_remont_kvartir_evroremont", "Капитальный евроремонт квартир в Санкт-Петербурге"),
				array("kompaniya_elitnyj_remont", "Элитный ремонт в Санкт-Петербурге"),
				array("lyuks_otdelka_pomeshhenij", "Люкс отделка помещений в Санкт-Петербурге"),
				array("lyuks_remont_domov", "Люкс ремонт домов в Санкт-Петербурге"),
				array("lyuks_remont_pomeshhenij", "Люкс ремонт помещений в Санкт-Петербурге"),
				array("otdelka_kvartir_evroremont", "Евроремонт квартир в Санкт-Петербурге"),
				array("prajs_list_na_evroremont", "Евроремонт квартир в Санкт-Петербурге"),
				array("rascenki_evrootdelki", "Евроремонт квартир в Санкт-Петербурге"),
				array("rascenki_na_evro_remonty", "Евроремонт квартир в Санкт-Петербурге"),
				array("remont_kvartir_dorogo", "Ремонт квартир дорого и качественно в Санкт-Петербурге"),
				array("remont_kvartir_dorogo_i_kachestvenno", "Ремонт квартир дорого и качественно в Санкт-Петербурге"),
				array("remont_kvartir_evroremont", "Ремонт квартир евроремонт в Санкт-Петербурге"),
				array("remont_kvartir_evroremont_dizajn", "Евроремонт квартир в Санкт-Петербурге"),
				array("remont_kvartir_otdelka_evroremont", "Евроремонт квартир в Санкт-Петербурге"),
				array("remont_kvartir_pod_evro", "Евроремонт квартир в Санкт-Петербурге"),
				array("remont_kvartir_ceny_evroremont", "Евроремонт квартир в Санкт-Петербурге"),
				array("remont_kvartiry_lyuks", "Ремонт квартир класса люкс в Санкт-Петербурге"),
				array("remont_elitnyx_domov", "Ремонт элитных домов в Санкт-Петербурге"),
				array("sdelat_dizajnerskij_remont_v_kvartire", "Дизайнерский ремонт в квартире в Санкт-Петербурге"),
				array("sdelat_elitnyj_remont", "Элитный ремонт в Санкт-Петербурге"),
				array("skolko_stoit_dizajnerskij_remont_kvartiry", "Дизайнерский ремонт квартиры в Санкт-Петербурге"),
				array("skolko_stoit_evro_remont", "Евроремонт квартир в Санкт-Петербурге"),
				array("skolko_stoit_evroremont", "Евроремонт квартир в Санкт-Петербурге"),
				array("skolko_stoit_evroremont_dvuxkomnatnoj_kvartiry", "Евроремонт квартир в Санкт-Петербурге"),
				array("skolko_stoit_evroremont_kvartiry", "Евроремонт квартир в Санкт-Петербурге"),
				array("skolko_stoit_evroremont_odnokomnatnoj_kvartiry", "Евроремонт квартир в Санкт-Петербурге"),
				array("skolko_stoit_evroremont_trexkomnatnoj_kvartiry", "Евроремонт квартир в Санкт-Петербурге"),
				array("skolko_stoit_kvadratnyj_metr_evroremonta", "Евроремонт квартир в Санкт-Петербурге"),
				array("smeta_na_evroremont", "Евроремонт квартир в Санкт-Петербурге"),
				array("smeta_na_evroremont_kvartiry", "Евроремонт квартир в Санкт-Петербурге"),
				array("sovremennyj_dizajnerskij_remont_kvartir", "Современный дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("srednyaya_cena_evroremonta", "Евроремонт квартир в Санкт-Петербурге"),
				array("stoimost_dizajnerskogo_remonta_kvartiry", "Современный дизайнерский ремонт квартир в Санкт-Петербурге"),
				array("stoimost_evro_remonta", "Евроремонт квартир в Санкт-Петербурге"),
				array("stoimost_evroremonta", "Евроремонт квартир в Санкт-Петербурге"),
				array("stoimost_evroremonta_za_kvadratnyj_metr", "Евроремонт квартир в Санкт-Петербурге"),
				array("stoimost_evroremonta_kvartiry", "Евроремонт квартир в Санкт-Петербурге"),
				array("stoimost_evroremonta_pod_klyuch", "Евроремонт квартир в Санкт-Петербурге"),
				array("stoimost_elitnogo_remonta", "Элитный ремонт в Санкт-Петербурге"),
				array("studiya_elitnogo_remonta", "Элитный ремонт в Санкт-Петербурге"),
				array("elitnaya_otdelka", "Элитная отделка в Санкт-Петербурге"),
				array("elitnaya_otdelka_domov", "Элитная отделка домов в Санкт-Петербурге"),
				array("elitnaya_otdelka_kvartir", "Элитная отделка квартир в Санкт-Петербурге"),
				array("elitnaya_otdelka_kvartir_pod_klyuch", "Элитная отделка квартир под ключ в Санкт-Петербурге"),
				array("elitnaya_otdelka_kottedzhej", "Элитная отделка коттеджей в Санкт-Петербурге"),
				array("elitnaya_otdelka_kottedzhej_pod_klyuch", "Элитная отделка коттеджей под ключ в Санкт-Петербурге"),
				array("elitnaya_otdelka_pomeshhenij", "Элитная отделка помещений в Санкт-Петербурге"),
				array("elitnye_otdelochnye_raboty", "Элитные отделочные работы в Санкт-Петербурге"),
				array("elitnyj_evroremont", "Элитный евроремонт в Санкт-Петербурге"),
				array("elitnyj_remont_kvartir", "Элитный ремонт квартир в Санкт-Петербурге"),
				array("elitnyj_remont_kvartir_i_domov", "Элитный ремонт квартир и домов в Санкт-Петербурге"),
				array("elitnyj_remont_kvartir_pod_klyuch", "Элитный ремонт квартир под ключ в Санкт-Петербурге"),
				array("elitnyj_remont_kvartir_stoimost", "Элитный ремонт квартир стоимость в Санкт-Петербурге"),
				array("elitnyj_remont_kvartir_ceny", "Элитный ремонт квартир цены в Санкт-Петербурге"),
				array("elitnyj_remont_kottedzhej", "Элитный ремонт коттеджей в Санкт-Петербурге"),
				array("elitnyj_remont_kottedzhej_pod_klyuch", "Элитный ремонт коттеджей под ключ в Санкт-Петербурге"),
				array("elitnyj_remont_pod_klyuch", "Элитный ремонт под ключ в Санкт-Петербурге"),
				array("avito_remont_kvartir", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("avito_samara_remont_kvartir", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("v_samare_remont_xrushhevok", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("vnutrennyaya_otdelka_doma", "Внутренняя отделка Вашего дома"),
				array("vnutrennyaya_otdelka_pomeshhenij", "Внутренняя отделка Вашего помещения"),
				array("ishhu_mastera_po_remontu_kvartiry", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("ishhu_shtukatura_dlya_remonta_v_kvartire", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("kak_deshevo_sdelat_remont_v_kvartire", "Дешевый и качественный ремонт квартир"),
				array("kak_nedorogo_sdelat_remont_v_kvartire", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("kak_sdelat_nedorogoj_remont_v_kvartire", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("kak_sdelat_remont_v_odnokomnatnoj_kvartire", "Ремонт Вашей однокомнатной квартиры по доступной цене"),
				array("kalkulyator_remonta_kvartir", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("kapitalnyj_remont_kvartir", "Капитальный ремонт Вашей квартиры по доступной цене"),
				array("kapitalnyj_remont_kvartir_v_samare", "Капитальный ремонт Вашей квартиры по доступной цене"),
				array("kapitalnyj_remont_kvartiry_samara", "Капитальный ремонт Вашей квартиры по доступной цене"),
				array("kvartirnyj_remont", "Квартирный ремонт под ключ по доступной цене"),
				array("kompleksnyj_remont_kvartiry_samara", "Комплексный ремонт Вашей квартиры по доступной цене"),
				array("kosmeticheskij_remont_kvartir", "Косметический ремонт Вашей квартиры по доступной цене"),
				array("kosmeticheskij_remont_kvartir_ceny", "Косметический ремонт Вашей квартиры по доступной цене"),
				array("kosmeticheskij_remont_pomeshhenij_v_samare", "Косметический ремонт помещений по доступной цене"),
				array("krasivye_remonty_kvartir", "Красивый ремонт Вашей квартиры по доступной цене"),
				array("luchshie_remonty_kvartir", "Красивый ремонт Вашей квартиры по доступной цене"),
				array("mastera_po_remontu_kvartir_nedorogo", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("najti_mastera_po_remontu_kvartir_chastnika", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("ooo_remont_kvartir", "Ремонт Вашей квартиры под ключ по доступной цене"),
				array("otdelka_dachnogo_doma_vnutri", "Отделка дачного дома внутри по доступной цене"),
				array("otdelka_derevyannogo_doma", "Отделка деревянного дома качественно и по доступной цене"),
				array("otdelka_doma_vnutri", "Отделка дома внутри качественно и по доступной цене"),
				array("otdelka_kvartir", "Отделка квартир качественно и по доступной цене"),
				array("otdelka_kvartir_v_samare", "Отделка квартир качественно и по доступной цене"),
				array("otdelka_kvartir_samara", "Отделка квартир качественно и по доступной цене"),
				array("otdelka_kvartiry_s_nulya", "Отделка квартиры с нуля качественно и по доступной цене"),
				array("otdelka_kvartiry_cena_za_kvadratnyj_metr", "Отделка квартиры качественно и по доступной цене"),
				array("otdelka_kottedzhej", "Отделка коттеджей качественно и по доступной цене"),
				array("otdelka_pomeshhenij", "Отделка помещений качественно и по доступной цене"),
				array("otdelka_pomeshhenij_v_samare", "Отделка помещений качественно и по доступной цене"),
				array("prajs_list_na_remont_kvartir", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("prajs_list_po_remontu_kvartir_2015_samara", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("prajs_remont_kvartir_samara", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("rascenki_na_remont_kvartir", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("rascenki_na_remont_kvartir_2015", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("rascenki_na_remont_kvartir_2015_v_samare", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("rascenki_na_remont_kvartir_na_2015_god", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("raschet_remonta_kvartiry_i_materialov_kalkulyator", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("raschet_stoimosti_remonta_kvartiry_kalkulyator_remonta", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("remont_2_komnatnoj_kvartiry", "Ремонт 2 комнатной квартиры качественно и по доступной цене"),
				array("remont_2_komnatnoj_xrushhevki", "Ремонт 2 комнатной хрущевки качественно и по доступной цене"),
				array("remont_3_x_k_kvartiry_stalinki", "Ремонт Вашей квартиры сталинки качественно и по доступной цене"),
				array("remont_v_dvuxkomnatnoj_xrushhevke", "Ремонт хрущевок  качественно и по доступной цене"),
				array("remont_v_kvartire_muzha", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("remont_v_odnushke", "Ремонт однокомнатной квартиры качественно и по доступной цене"),
				array("remont_v_stalinke", "Ремонт сталинки под ключ качественно и по доступной цене"),
				array("remont_v_xrushhevke", "Ремонт хрущевок  качественно и по доступной цене"),
				array("remont_v_xrushhevke_1x_komnatnoj", "Ремонт хрущевок  качественно и по доступной цене"),
				array("remont_v_xrushhevke_2_komnatnoj_smezhnoj", "Ремонт хрущевок  качественно и по доступной цене"),
				array("remont_v_xrushhevke_2x_komnatnoj", "Ремонт хрущевок  качественно и по доступной цене"),
				array("remont_vnutrennix_pomeshhenij_zdaniya", "Ремонт внутренних помещений качественно и по доступной цене"),
				array("remont_zhilyx_pomeshhenij", "Ремонт жилых помещений качественно и по доступной цене"),
				array("remont_zagorodnogo_doma", "Ремонт загородного дома качественно и по доступной цене"),
				array("remont_i_otdelka_kvartir", "Ремонт / отделка квартир качественно и по доступной цене"),
				array("remont_i_otdelka_kvartir_i_domov", "Ремонт / отделка квартир качественно и по доступной цене"),
				array("remont_i_otdelka_kvartir_samara", "Ремонт / отделка квартир качественно и по доступной цене"),
				array("remont_i_otdelka_pomeshhenij", "Ремонт и отделка помещений качественно и по доступной цене"),
				array("remont_kvartir", "Ремонт Вашей квартиры под ключ качественно и по доступной цене"),
				array("remont_kvartir_2015_god", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_kvartir_v_kontakte", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_kvartir_v_samare", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_kvartir_v_samare_na_avito", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_kvartir_v_samare_obyavleniya", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_kvartir_v_samare_otzyvy", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_kvartir_v_samare_pod_klyuch", "Ремонт Вашей квартиры в под ключ качественно и по доступной цене"),
				array("remont_kvartir_v_samare_pod_klyuch_ceny", "Ремонт Вашей квартиры в под ключ качественно и по доступной цене"),
				array("remont_kvartir_v_samare_prajs_list", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("remont_kvartir_v_samare_rascenki", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("remont_kvartir_v_samare_firmy", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("remont_kvartir_v_samare_ceny", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("remont_kvartir_i_ofisov", "Ремонт Вашей квартиры / офисов качественно и по доступной цене"),
				array("remont_kvartir_nedorogo", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_kvartir_otdelochnye_raboty", "Ремонт-отделка квартир качественно и по доступной цене"),
				array("remont_kvartir_otzyvy", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_kvartir_pod_klyuch", "Ремонт Вашей квартиры под ключ качественно и по доступной цене"),
				array("remont_kvartir_realnyx", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_kvartir_samara", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_kvartir_samara_obyavleniya", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_kvartir_samara_otzyvy", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_kvartir_samara_ceny", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_kvartir_ceny", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("remont_kvartiry_v_samare_nedorogo", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_kvartiry_v_samare_nedorogo_kachestvenno_firmy", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_kvartiry_v_samare_stoimost", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_kvartiry_v_stalinke", "Ремонт Вашей квартиры сталинки качественно и по доступной цене"),
				array("remont_kvartiry_pod_klyuch_samara", "Ремонт Вашей квартиры под ключ качественно и по доступной цене"),
				array("remont_kommercheskix_pomeshhenij", "Ремонт коммерческих помещений качественно и по доступной цене"),
				array("remont_kottedzhej", "Ремонт коттеджей качественно и по доступной цене"),
				array("remont_kottedzhej_v_samare", "Ремонт коттеджей качественно и по доступной цене"),
				array("remont_kottedzhej_pod_klyuch", "Ремонт коттеджей под ключ качественно и по доступной цене"),
				array("remont_nezhilyx_pomeshhenij", "Ремонт нежилых помещений качественно и по доступной цене"),
				array("remont_nezhilyx_pomeshhenij_v_samare", "Ремонт нежилых помещений качественно и по доступной цене"),
				array("remont_odnokomnatnoj_kvartiry", "Ремонт однокомнатной квартиры качественно и по доступной цене"),
				array("remont_odnokomnatnoj_kvartiry_pod_klyuch", "Ремонт однокомнатной квартиры качественно и по доступной цене"),
				array("remont_podvalnyx_pomeshhenij", "Ремонт подвальных помещений качественно и по доступной цене"),
				array("remont_pomeshhenij", "Ремонт помещений качественно и по доступной цене"),
				array("remont_pomeshhenij_v_samare", "Ремонт помещений качественно и по доступной цене"),
				array("remont_pomeshhenij_pod_klyuch", "Ремонт помещений под ключ  качественно и по доступной цене"),
				array("remont_pomeshhenij_samara", "Ремонт помещений качественно и по доступной цене"),
				array("remont_proizvodstvennyx_pomeshhenij", "Ремонт производственных помещений качественно и по доступной цене"),
				array("remont_srubovogo_doma", "Ремонт срубового дома качественно и по доступной цене"),
				array("remont_studii_20_kv_m", "Ремонт квартиры-студии качественно и по доступной цене"),
				array("remont_studij_20_kv", "Ремонт квартиры-студии качественно и по доступной цене"),
				array("remont_trexkomnatnoj_kvartiry_ceny_na_2015_god", "Ремонт трехкомнатной квартиры качественно и по доступной цене"),
				array("remont_xrushhevki_cena", "Ремонт хрущевки качественно и по доступной цене"),
				array("sajt_uslug_po_remontu_kvartir", "Услуг по ремонту квартир качественно и по доступной цене"),
				array("samara_remont_kvartir_nedorogo", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("sdelat_remont_v_kvartire", "Сделаем ремонт в Вашей квартире качественно и по доступной цене"),
				array("skolko_stoit_remont_4_komnatnoj_kvartiry", "Ремонт 4 комнатной квартиры  качественно и по доступной цене"),
				array("smeta_na_vnutrennyuyu_otdelku_doma", "Внутреннюю отделка дома качественно и по доступной цене"),
				array("smeta_na_remont_kvartiry", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("smeta_na_remont_pomeshheniya", "Ремонт помещения качественно и по доступной цене"),
				array("smeta_otdelki_kvartiry", "Отделка квартиры качественно и по доступной цене"),
				array("sovremennaya_otdelka_doma", "Современная отделка дома качественно и по доступной цене"),
				array("sovremennaya_otdelka_kvartir", "Современная отделка квартир качественно и по доступной цене"),
				array("sovremennyj_remont_odnokomnatnoj_kvartiry", "Современный ремонт Вашей квартиры качественно и по доступной цене"),
				array("srednyaya_stoimost_remonta_kvartiry_za_kvadratnyj_metr", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("staraya_kvartira_remont", "Ремонт старых квартир качественно и по доступной цене"),
				array("stoimost_kvadratnogo_metra_remonta_kvartiry_pod_klyuch", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("stoimost_predchistovoj_otdelki_kvartiry", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("stoimost_remonta_kvartiry", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("stoimost_remonta_kvartiry_za_1_kv_m", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("stoimost_chistovoj_otdelki_kottedzha", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("studiya_remonta_samara", "Услуги по ремонту квартир качественно и по доступной цене"),
				array("uslugi_masterov_po_remontu_kvartir", "Услуги по ремонту квартир качественно и по доступной цене"),
				array("uslugi_po_remontu_kvartir_v_samare", "Услуги по ремонту квартир качественно и по доступной цене"),
				array("firmy_po_remontu_kvartir", "Услуги по ремонту квартир качественно и по доступной цене"),
				array("ceny_na_remont_kvartir_v_2015_godu", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("ceny_na_remont_kvartir_v_samare_2015", "Качественный ремонт Вашей квартиры по доступной цене"),
				array("chistovaya_otdelka_doma", "Чистовая отделка дома качественно и по доступной цене"),
				array("chto_vxodit_v_kosmeticheskij_remont_kvartiry", "Косметический ремонт Вашей квартиры качественно и по доступной цене"),
				array("chto_takoe_chistovaya_otdelka_kvartiry", "Чистовая отделка квартиры качественно и по доступной цене"),
				array("ekonom_remont_kvartiry_pod_klyuch_s_cenami", "Эконом ремонт Вашей квартиры качественно и по доступной цене"),
				array("etalon_remont_kvartir", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("vo_skolko_oboshelsya_remont_v_novostrojke", "Ремонт новостроек качественно и по доступной цене"),
				array("evroremont_novostrojki", "Евроремонт новостройки качественно и по доступной цене"),
				array("kak_prinimat_kvartiru_v_novostrojke_bez_otdelki", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("kak_sdelat_remont_v_novostrojke", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("kalkulyator_stoimosti_remonta_kvartiry_v_novostrojke", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("otdelka_kvartir_pod_klyuch_v_novostrojke_ceny", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("otdelka_novostoek", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("poetapnyj_remont_kvartiry_v_novostrojke", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("primernaya_smeta_na_remont_kvartiry_v_novostrojke", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("raschet_stoimosti_remonta_kvartiry_v_novostrojke", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("remont_v_novostrojkax_samara", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("remont_v_novostrojke", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("remont_v_novostrojke_po_shagam", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("remont_kvartir_v_novostrojkax_ceny", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("remont_kvartir_v_novostrojke", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("remont_kvartir_v_novostrojke_v_samare", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("remont_kvartir_v_novostrojke_samara", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("remont_kvartiry_s_nulya_v_novostrojke", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("remont_novostroek_v_samare", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("remont_pod_klyuch_s_materialami_v_novostrojke", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("skolko_stoit_remont_v_odnokomnatnoj_novostrojke", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("skolko_stoit_remont_kvartiry_v_novostrojke", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("skolko_stoit_remont_odnokomnatnoj_kvartiry_v_novostrojke", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("skolko_stoit_chernovoj_remont_v_novostrojke", "Черновой ремонт в новостройке качественно и по доступной цене"),
				array("smeta_remonta_odnokomnatnoj_kvartiry_v_novostrojke", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("stoimost_remonta_v_novostrojke_s_materialami_2015", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("stoimost_chernovogo_remonta_v_novostrojke_kalkulyator", "Ремонт Вашей квартиры в новостройке качественно и по доступной цене"),
				array("chernovoj_remont_kvartiry_s_nulya_v_novostrojke", "Черновой ремонт новостроек с нуля качественно и по доступной цене"),
				array("chistovaya_otdelka_kvartiry_v_novostrojke_chto_eto", "Чистовая отделка новостройки качественно и по доступной цене"),
				array("vnutrennij_remont", "Внутренний ремонт Вашей квартиры качественно и по доступной цене"),
				array("vnutrennyaya_otdelka", "Внутренняя отделка квартир качественно и по доступной цене"),
				array("vnutrennyaya_otdelka_dachi", "Внутренняя отделка дачи качественно и по доступной цене"),
				array("vnutrennyaya_otdelka_sruba", "Внутренняя отделка сруба качественно и по доступной цене"),
				array("vnutrennyaya_otdelka_sruba_ceny", "Внутренняя отделка сруба качественно и по доступной цене"),
				array("kak_sdelat_kosmeticheskij_remont_nedorogo", "Косметический ремонт качественно и по доступной цене"),
				array("kosmeticheskij_remont", "Косметический ремонт качественно и по доступной цене"),
				array("kosmeticheskij_remont_v_samare", "Косметический ремонт качественно и по доступной цене"),
				array("kosmeticheskij_remont_v_samare_ceny", "Косметический ремонт качественно и по доступной цене"),
				array("kosmeticheskij_remont_kvartir", "Косметический ремонт качественно и по доступной цене"),
				array("kosmeticheskij_remont_kvartir_ceny", "Косметический ремонт качественно и по доступной цене"),
				array("kosmeticheskij_remont_stoimost_kvadratnogo_metra", "Косметический ремонт качественно и по доступной цене"),
				array("otdelka_pod_klyuch_cena_za_m2", "Отделка под ключ качественно и по доступной цене"),
				array("otdelka_pod_chistovuyu_chto_eto", "Отделка под чистовую качественно и по доступной цене"),
				array("pervonachalnaya_obrabotka_kvartiry_chernovaya_otdelka", "Черновая отделка квартиры качественно и по доступной цене"),
				array("predchistovaya_otdelka", "Предчистовая отделка квартиры качественно и по доступной цене"),
				array("remont_kvartir_v_samare_pod_klyuch", "Ремонт Вашей квартиры под ключ качественно и по доступной цене"),
				array("remont_kvartir_v_samare_pod_klyuch_ceny", "Ремонт Вашей квартиры под ключ качественно и по доступной цене"),
				array("remont_kvartir_pod_klyuch", "Ремонт Вашей квартиры под ключ качественно и по доступной цене"),
				array("remont_kvartiry_pod_klyuch_samara", "Ремонт Вашей квартиры под ключ качественно и по доступной цене"),
				array("remont_odnokomnatnoj_kvartiry_pod_klyuch", "Ремонт Вашей квартиры под ключ качественно и по доступной цене"),
				array("remont_pod_klyuch", "Ремонт Вашей квартиры под ключ качественно и по доступной цене"),
				array("remont_pod_klyuch_v_samare", "Ремонт Вашей квартиры под ключ качественно и по доступной цене"),
				array("remont_pod_klyuch_v_samare_ceny", "Ремонт Вашей квартиры под ключ качественно и по доступной цене"),
				array("remont_pod_klyuch_samara", "Ремонт Вашей квартиры под ключ качественно и по доступной цене"),
				array("remont_pod_klyuch_samara_ceny", "Ремонт Вашей квартиры под ключ качественно и по доступной цене"),
				array("remont_ekonom_klassa", "Ремонт эконом класса качественно и по доступной цене"),
				array("s_chego_nachinat_remont_chernovoj_otdelki", "Черновая отделка квартир качественно и по доступной цене"),
				array("stoimost_kvadratnogo_metra_remonta_kvartiry_pod_klyuch", "Ремонт под ключ качественно и по доступной цене"),
				array("stoimost_predchistovoj_otdelki_kvartiry", "Предчистовая отделка квартиры качественно и по доступной цене"),
				array("chernovaya_otdelka", "Черновая отделка квартиры качественно и по доступной цене"),
				array("chernovaya_otdelka_kvartiry", "Черновая отделка квартиры качественно и по доступной цене"),
				array("vnutrennie_otdelochnye_raboty_rascenki_samara", "Внутренние отделочные работы качественно и по доступной цене"),
				array("osmechivanie_remontnyx_rabot", "Осмечивание ремонтных работ в квартирах за 1 день"),
				array("otdelka_i_remont_firmy", "Услуги по отделке и ремонту качественно и по доступной цене"),
				array("otdelochnye_raboty", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("otdelochnye_raboty_v_samare", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("otdelochnye_raboty_v_samare_ceny", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("otdelochnye_raboty_obyavlenie", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("otdelochnye_raboty_prajs_list", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("otdelochnye_raboty_rascenki_2015", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("otdelochnye_raboty_rascenki_samara", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("otdelochnye_raboty_samara", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("otdelochnye_raboty_smyshlyaevka", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("otdelochnye_raboty_cena_za_metr", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("prajs_list_na_otdelochnye_raboty_2015", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("prajs_list_na_otdelochnye_raboty_2015_samara", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("prajs_na_otdelochnye_raboty", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("prajs_na_otdelochnye_raboty_2015", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("prajs_na_otdelochnye_raboty_2015_samara", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("prajs_na_otdelochnye_raboty_v_samare_2015", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("prajs_na_otdelochnye_raboty_samara", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("prajsy_na_otdelochnye_raboty_v_samare", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("prejskurant_cen_na_otdelochnye_raboty_2015", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("rascenki_na_vnutrennie_otdelochnye_raboty", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("rascenki_na_vnutrennie_otdelochnye_raboty_v_samare", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("rascenki_na_otdelochnye_raboty", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("rascenki_na_otdelochnye_raboty_v_samare", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("rascenki_na_otdelochnye_raboty_na_2015_god", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("remont_i_otdelka", "Ремонт-отделка квартир качественно и по доступной цене"),
				array("remont_i_otdelka_kvartir", "Ремонт-отделка квартир качественно и по доступной цене"),
				array("remont_i_otdelka_kvartir_samara", "Ремонт-отделка квартир качественно и по доступной цене"),
				array("remont_kvartir_otdelochnye_raboty", "Ремонт-отделка квартир качественно и по доступной цене"),
				array("remont_otdelka_samara", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("remontno_montazhnye_raboty", "Ремонтно монтажные работы качественно и по доступной цене"),
				array("remontno_otdelochnye_raboty", "Ремонтно отделочные работы качественно и по доступной цене"),
				array("s_chego_nachinat_remont_chernovoj_otdelki", "Ремонт черновой отделки качественно и по доступной цене"),
				array("smeta_na_vnutrennie_otdelochnye_raboty", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("smeta_na_otdelochnye_raboty_2015_god", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("stoimost_vnutrennix_otdelochnyx_rabot", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("stoimost_otdelochnyx_rabot", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("stoimost_otdelochnyx_rabot_v_samare_2015", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("stoimost_otdelochnyx_rabot_za_m2", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("stoimost_otdelochnyx_rabot_samara", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("stoimost_otdelochnyx_rabot_samare", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("stoimost_remontnyx_rabot_v_kvartire_kalkulyator", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("stoimost_remontnyx_rabot_za_kvadratnyj_metr", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("stoimost_remontnyx_rabot_prajs_list", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("cena_otdelochnyx_rabot_za_m2", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("ceny_na_otdelochnye_raboty", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("ceny_na_otdelochnye_raboty_v_samare_2015", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("ceny_na_remontno_otdelochnye_raboty_2015", "Отделочные работы Вашей квартиры качественно и по доступной цене"),
				array("remont_kuxon_", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_spalen_", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("otdelka_pomeshhenij_", "Отделка помещений качественно и по доступной цене"),
				array("remont_kvartir_", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("otdelochnye_raboty_", "Отделка помещений качественно и по доступной цене"),
				array("interer_doma_", "Дизайнерский ремонт квартир и домов качественно и по доступной цене"),
				array("interer_kvartiry_", "Дизайнерский ремонт квартир и домов качественно и по доступной цене"),
				array("dizajn_interera_", "Дизайнерский ремонт квартир и домов качественно и по доступной цене"),
				array("sovremennyj_interer_", "Дизайнерский ремонт квартир и домов качественно и по доступной цене"),
				array("interer_detskoj_", "Дизайнерский ремонт квартир и домов качественно и по доступной цене"),
				array("interer_xrushhevki_", "Дизайнерский ремонт квартир и домов качественно и по доступной цене"),
				array("idei_interera_", "Дизайнерский ремонт квартир и домов качественно и по доступной цене"),
				array("remont_v_novostrojkax_", "Ремонт квартир в новостройках качественно и по доступной цене"),
				array("evroremont_", "Евроремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_v_xrushhevkax_", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_vannyx_komnat_", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_pomeshhenij_", "Ремонт помещений качественно и по доступной цене"),
				array("kosmeticheskij_remont_kvartir_", "Косметический ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_gostinyx_", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("otdelka_v_xrushhevkax_", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_detskix_", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("otdelka_vannyx_komnat_", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_zalov_", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("otdelka_domov_", "Отделка Вашего дома качественно и по доступной цене"),
				array("remont_komnat_", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("remont_kottedzhej_", "Ремонт Вашего коттеджа качественно и по доступной цене"),
				array("otdelka_kvartir_", "Ремонт Вашей квартиры качественно и по доступной цене"),
				array("otdelka_kottedzhej_", "Отделка Вашего коттеджа качественно и по доступной цене"),
				array("otdelka_kuxon_", "Ремонт Вашей квартиры качественно и по доступной цене")
			);
		# end initialization
	}
	public function getHeader(&$GET) {
		if (array_key_exists("utm_multi", $GET)){
			$term = $GET["utm_multi"];
			for ($i=0; $i <count($this->arr_heading); $i++) {
				if ($this->arr_heading[$i][0] == $term)
					return $this->arr_heading[$i][1];
			}
		}
		return "Качественный ремонт Вашей<br>квартиры по доступной цене";
	}
	public function getRequired(&$GET) {
		if (array_key_exists("utm_multi", $GET)){
			$term = $GET["utm_multi"];
			for ($i=0; $i <count($this->arr_heading); $i++) {
				if ($this->arr_heading[$i][0] == $term)
					return $this->arr_heading[$i][0];
			}
		}
		return "";
	}
}
# ?utm_source=yandex&utm_medium=cpc&utm_campaign={campaign_id}&utm_content={ad_id}&utm_term={keyword}&utm_multi=diagnostika_elektriki
?>